### ISSUE TITLE
Recording audio on stm32f4 with max9814 save to  external sd card

### ISSUE THREAD

**Issue by JoelMuhanguzi** [stm32duino/X-NUCLEO-53L4A2#3]
Hello, which library can I use to record audio to an sd card by means of a microphone module like the max9814 or max4466  while using an stm32f411 blackpill board?

**Comment by cparata** [comment]
Hello @JoelMuhanguzi ,
I don't know the max9814 and max4466 audio modules, so I cannot help you. Please, could you avoid to open issues on libraries that are out of the scope of your request? It is better to submit this kind of questions in the community forum.
Best Regards,
Carlo
